# Site settings
title: A summer with Sugarlabs and Music :) 
email: aneesh@sugarlabs.org
description: "My experiments and documentation while I explore music and code with sugarlabs."
baseurl: "http://lionaneesh.github.io/"
url: "http://lionaneesh.github.io/"

# Build settings
markdown: kramdown
permalink: pretty
